### ISSUE TITLE
Error loading module lua:8: ')' expected near '?'

### ISSUE THREAD

**Issue by kamaldua65** [eduardoafs/mod_muc_chat_recording#1]
When I restart prosody get an error:
Unable to load module 'muc_chat_recording': .../usr/share/jitsi-meet/prosody-plugins/mod_muc_chat_recording.lua:8: ')' expected near '?'

I have no knowledge of Lua, ,however I think line 8 is just checking if path end with /
I commented line 8 , it loads perfectly but still get errors:
Attempt to read a non-existent global 'getFileName'

Am I missing someting. Prosody version: 0.11.7
Thanks

**Comment by eduardoafs** [comment]
Hey @quidlab 
Apparently there is nothing wrong with the code itself, but prosody environment can be pretty tricky sometimes.
Can you please look for lua version? 
Also, please check any other module that was imported right before this one.

**Comment by kamaldua65** [comment]
Thank you for quick response. it is Lua 5.2.4 
I will check other modules as well.

**Comment by kamaldua65** [comment]
I managed to solve issue, Thank you.
